title: Venkata Saikrishna Dussa
logo: /assets/img/profilepic.jpeg
description: Machine Learning and Artificial Intelligence Engineer.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
